HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

setopt INC_APPEND_HISTORY_TIME # adds history incrementally
setopt EXTENDED_HISTORY # add timestamps to history
setopt HIST_IGNORE_ALL_DUPS # don't record dupes in history
setopt HIST_REDUCE_BLANKS

. ~/.dots/configs/zsh/aliases

if test -n "$(command -v starship)"; then
  USE_STARSHIP=true
else
  USE_STARSHIP=false
fi

if $USE_STARSHIP; then
  eval "$(starship init zsh)"
fi
