name: MacOS Test
on: push

jobs:
  macos-local:
    name: Local Install
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          path: .dots
      - name: Perform Installation
        run: |
          cd .dots && \
          sh install.sh
        env:
          HOME: /Users/runner/work/dotfiles/dotfiles
